{
  "headers": {
    "host": "localhost:8082",
    "connection": "keep-alive",
    "content-length": "230",
    "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
    "sec-ch-ua-platform": "\"Windows\"",
    "content-type": "application/json",
    "accept": "*/*",
    "origin": "http://localhost:8082",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8082/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "jenkins-timestamper-offset=-19800000; jenkins-timestamper=system; jenkins-timestamper-local=true"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/employees",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/employees",
  "listenerPath": "/api/*",
  "relativePath": "/api/employees",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/employees",
  "rawRequestPath": "/api/employees",
  "remoteAddress": "/127.0.0.1:52509",
  "requestPath": "/api/employees"
}